BaseURL = "http://galooph.com/"
languageCode = "en-gb"
title = "The ramblings of galooph"
theme = "cactus"
[indexes]
    category = "categories"
[permalinks]
    post = "/blog/:year/:month/:day/:title/"
metadataformat = "toml"

[params]
    name = "galooph"
    full_name = "Dan Smith"
    description = "The ramblings of galooph"
    bio = "Coder – Engineer - Hacker"
    # Enter optionally your twitter account
    twitter = "galooph"
    # Disable comments by leaving disqusShortname empty
    disqusShortname = "galoophcom"
    # Enter your tracking code to enable Google Analytics
    googleAnalytics = "UA-47063860-1"
    enableRSS = true
    facebook_app_id = "576775086"
    facebook_page = "https://www.facebook.com/galooph"
    # The default opengraph image to share on facebook
    facebook_image = ""
    # The default twitter card image
    twitter_card_image = ""